### ISSUE TITLE
Live Lantern Dashboard does not load. 

### ISSUE THREAD

**Issue by Liam-McGoldrick-Legacy** [onc-healthit/lantern-back-end#372]
When accessing the Lantern dashboard at:
https://lantern.healthit.gov/?tab=dashboard_tab
Per the url at:
https://www.healthit.gov/topic/interoperability/investments/lantern-project

The page will first spin like this for some time:
![image](https://github.com/onc-healthit/lantern-back-end/assets/170690377/2ed58650-fed8-47c9-856e-5da2a7784d3d)
It never finishes, and if I try to refresh it does not even show the UI on subsequent loads. 

Sometimes it will timeout and I see: 
![image](https://github.com/onc-healthit/lantern-back-end/assets/170690377/8a03f822-1672-4ed8-a706-9bd751817efe)

Its been doing things like this for a while, but previously it would load successfully after a few tries. No longer is this the case. For any CDN related debugging, I am located in Florida.

**Comment by nathanloyer** [comment]
This is still an issue for me. I take it nobody is looking at this?

**Comment by Liam-McGoldrick-Legacy** [comment]
@nathanloyer I have been waiting a while!

**Comment by nathanloyer** [comment]
It appears to be working at the moment. Is it maybe just going down for extended periods when it is refreshing data or rebooting?

**Comment by nathanloyer** [comment]
I reached out on chat.fhir.org as well

https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Lantern

**Comment by vishnu-mettles** [comment]
Lantern dashboard is being monitored daily. Closing this issue
